version: 2
updates:
    - package-ecosystem: "gradle"
      directory: "/"
      schedule:
          interval: "weekly"
      reviewers:
          - "gurkenlabs"

    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
      rebase-strategy: "disabled"
      reviewers:
          - "nightm4re94"
          - "steffen-wilke"
