version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gradle-minor:
        update-types:
          - "minor"
      gradle-patch:
        update-types:
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions-minor:
        update-types:
          - "minor"
      github-actions-patch:
        update-types:
          - "patch"
