name: Greetings

on:
  pull_request_target:
    types:
      - opened
  issues:
    types:
      - opened

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Thank you for your reporting your first LITIENGINE issue! We are looking forward to your further contributions.'
          pr-message: 'Amazing, your first Pull Request in the LITIENGINE repository! You have earned the rank of "contributor" - let us know your nickname in the Forum and on Discord so we can reward you with the new role :).'
