name: Package utiLITI

on:
  workflow_dispatch

jobs:
  package:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    name: Package distribution
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 19

      - name: Package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            jpackage
            -Prelease=true

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: utiLITI-${{ runner.os }}
          path: build/litiengine-utiliti/jpackage




